swagger:
  enabled: true
  title: DTC_OMG
  description: 接口文档
  version: 1.0.0
  base-package: com.dtcomg.web.controller, com.dtcomg.system.controller
  contact:
    name: API 支持团队
    email: support@example.com
  security:
    name: Authorization
    type: apiKey
    in: header

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml